### ISSUE TITLE
로그아웃 다이얼로그의 생김새가 이상함

### ISSUE THREAD

**Issue by RieLCho** [CSID-DGU/2021-1-OSSP2-Barcode-8#1]
![KakaoTalk_20210503_011321641](https://user-images.githubusercontent.com/13748138/116819841-e20a9100-abac-11eb-8207-f4321f0ff3ff.jpg)

NO YES 버튼에 이상한 음영이 져 있습니다.

**Comment by eogus0512** [comment]
![image](https://user-images.githubusercontent.com/71585151/116822857-2fdac580-abbc-11eb-9b76-c2263d15c4a7.png)

63c3a06467f1966a6ed510b41c71059f041c6978

수정완료
