### ISSUE TITLE
SettingActivity와 해당 액티비티의 Child Activities 완성하기

### ISSUE THREAD

**Issue by RieLCho** [CSID-DGU/2021-1-OSSP2-Barcode-8#4]
- 계정 정보를 제외한 Setting 화면을 완성해야 함
- 사용자의 리뷰를 관리할 수 있는 리뷰 관리
- 문의란 (이메일을 보낼 수 있도록 함)
- 오픈소스 고지
- 혹은 개발 중 필요한 부분은 수시로 추가되거나 제거될 수 있음

![설정화면](https://user-images.githubusercontent.com/13748138/116820219-d28c4780-abae-11eb-8cfa-3a72c959f9bf.png)

**Comment by eogus0512** [comment]
구현 완료
