### ISSUE TITLE
MainActivity의 ActionBar Title 색과 폰트가 바뀌지 않음

### ISSUE THREAD

**Issue by RieLCho** [CSID-DGU/2021-1-OSSP2-Barcode-8#8]
![InkedKakaoTalk_rZ7x1AbCms_LI](https://user-images.githubusercontent.com/13748138/116820694-3879ce80-abb1-11eb-86b4-aea801eee7ad.jpg)

~~~
ActionBar actionBar = getSupportActionBar();
Spannable text = new SpannableString(actionBar.getTitle());
text.setSpan(new ForegroundColorSpan(Color.BLACK), 0, text.length(), Spannable.SPAN_INCLUSIVE_INCLUSIVE);
actionBar.setTitle(text);
~~~
로 색은 바꿀 수 있는데 FAB에 버그가 생김

좋은 수가 생각나지 않으면 이미지로 만들어서 App Logo 대신 집어넣는 방식으로 가야 할 듯

**Comment by eogus0512** [comment]
![image](https://user-images.githubusercontent.com/71585151/116822891-5a2c8300-abbc-11eb-8f31-a41a7113f8da.png)
63c3a06467f1966a6ed510b41c71059f041c6978

수정 완료
